### ISSUE TITLE
Large differences with results from preprint

### ISSUE THREAD

**Issue by GuillaumeHolley** [baharpan/dynboss#1]
Hi there,

Thank you for your preprint publication, it was an interesting read.

I was trying yesterday to reproduce one of the experiment of the paper and the numbers I get are very different from the ones in the preprint. I was wondering if you could have a look at them and help me figure out what I am missing?

The experiment I was trying to reproduce is the graph construction from the full set of E. coli reads. I have downloaded the dataset `ERX002508` from SRA which corresponds to ~28 million reads. The preprint says (Table 2) that construction for dynBOSS takes about 7 min with a peak of RAM at 187 MB while Bifrost uses 1h 20min for 2.6 GB of RAM. Here are the commands I ran and the number I get for the whole pipeline (time + RAM peak) to construct the graph from input FASTQ to output graph as Bifrost does:

- DynBOSS:
```
./dsk-1.6906/dsk s_6.fastq 31 -m 187
./cosmo-pack s_6.solid_kmers_binary 
./cosmo-build-dyn s_6.solid_kmers_binary.packed

dsk: 23 min 43 s | 200.5 MB
cosmo-pack: 7 min | 23 GB
cosom-build-dyn: 1 h 44 min 50 s | 905.5 MB
---------------------------------------------------------
Total: 2 h 15 min 33 s | 23 GB
```
- Bifrost:
```
Bifrost build -t 1 -k 31 -v -r s_6.fastq -o s_6_graphBifrost_k31

Bifrost: 50 min 22 s | 3.63 GB
------------------------------
Total: 50 min 22 s | 3.63 GB
```

In these results, Bifrost is 2.69 times faster than DynBOSS and uses 6.33 times less memory, which is in direct contradiction with what the preprint reports. Do you know if I am missing a command option somewhere or something like that? I also ran all the commands on a standard mechanical hard-drive, did the experiments from the paper were run on an SSD hard-drive or a RAM-based partition? That could explain partially the difference in the results.

Thank you for your time and help.

Guillaume

**Comment by baharpan** [comment]
Thanks for trying DynamicBOSS. There are some improvements that I will add to the repository this week. I apologize that it is not updated yet, I was busy with my Ph.D. defense till last week. However, I can address some of the conflicts. All experiments are performed on the dataset ERX002508 which we call 28M-e on normal platter-based SAS HDs in a RAID 5 configuration.

DynamicBOSS:

Time:

1- DSK in this repository is not updated (I will update it this week). Using the latest version of DSK (https://github.com/GATB/dsk) I have the below runtime:
```
dsk -abundance-min 0 -file 28M_e.fa -kmer-size 31
CPU Time: 00:05:56
Wall Clock Time: 00:00:27
```
However, we have not included DSK time to the reported runtime of DynamicBOSS. I understand that Bifrost starts from the Fasta/Fastq file, and I make sure to make this point clear in the manuscript. 


2- DynamicBOSS and BOSS by default add the reverse complement of the kmers that do not have one in the read set. To be fair, in our experiment we have turned off this option since all methods are building the graph on available kmers in the read set. You can turn off this option which is called “revcomps” in the Makefile. (In short please make sure that you do not have the flag “-DADD_REVCOMPS” while compiling the source codes. Running DynamicBOSS with this option will increase the number of edges and hence the building time; however, the max runtime of cosmo-build-dyn I would expect --as shown below-- for this dataset  is 00:09:49 and I could not recreate the “1 h 44 min 50 s” in your experiment.
```
#Running cosmo-pack and cosmo-build-dyn with “revcomps” on:

cosmo-pack 28M_e.solid_kmers_binary
Time: 00:05:02

cosmo-build-dyn 28M_e.solid_kmers_binary.packed 
k : 31
num_nodes() : 620676646
num_edges() : 642073709
Total size : 446.054 MB
Bits per edge : 5.82763 Bits
Time: 00:09:49

Total Time: 00:14:51
```
```
#Running cosmo-pack and cosmo-build-dyn with “revcomps” off (what we report in the paper):

cosmo-pack 28M_e.solid_kmers_binary
Time: 00:02:50

cosmo-build-dyn 28M_e.solid_kmers_binary.packed
k : 31
num_nodes() : 258318223
num_edges() : 269218149
Total size : 187.033 MB
Bits per edge : 5.82778 Bits
Time: 00:04:17

Total Time: 00:07:07
```
Would you please let me know if you get the same number of nodes/edges while running cosmo-build-dyn (with turning “revcomps” off)? This will help me understand why the runtime is way larger on your end.

Memory:

As we mention in the paper: “We compared the time required to construct the graph, **the size of the de Bruijn graph in memory** and stored on hard disk ...” This means by memory we do not refer to memory usage while construction, instead we have calculated the size of the data structure while loaded into the memory. To measure this value for Bifrost, I have followed your suggestion (in our conversation via email on Sep 2019) which was “Create a tiny program whose single task is to read the GFA file of the graph from disk and measure the memory used by the program just after reading”. That is why the memory I report for Bifrost in Table 2 (**2.6 GB**) is smaller than the value you report--which is peak memory for constructing the graph-- (3.63 GB). As shown in the above experiment with "revcomps" off, the Total size of DynamicBOSS in the memory is:
“**Total size : 187.033 MB**” which is reported in the column ‘Memory’ of Table 2. Also, please note that the value “Bits per edge” of DynamicBOSS in the above experiment is on the memory (5.8 bits) which is slightly different from the same measure in the disk --5.7 bits that I report in the column ‘Disk’ of Table 2 in the paper.  

Also, we have made significant improvements in construction memory usage recently. I will push the latest improvements this week.



Bifrost:

The runtime I report in the paper were based on the experiments I did on Nov/01/2019:
```
bifrost build -t 1 -k 31 -o 28M_e-refbased.bfrst -r 28M_e.fa
Time: 1:20:23
```
I understand that there was an update in Bifrost this year, so I will update the experiments in the manuscript. I have pulled the new version and below is the new runtime:
```
bifrost build -t 1 -k 31 -o 28M_e-refbased.bfrst-test -r 28M_e.fa
Time: 01:06:55
```
In these results DynamicBOSS is >11 times and >9 times faster than old and new versions of Bifrost respectively. Also the size of DynamicBOSS loaded to memory was 187 MB while Bifrost was 2.6 GB. Please let me know if I am missing something in Bifrost commands.

I hope this infomation is helpful, and once again I am sorry that the repository is not updated yet.

Bahar

**Comment by GuillaumeHolley** [comment]
Dear Bahar,

Thank you for your detailed answer. I am looking forward to try the improvements that you will bring to DynBOSS. So far, I haven't been able to reproduce the running time that you have been showing, even with a different machine and a much faster hard drive, so a large difference regarding the running time remains. More details below:

1 - Thank you for making that point more clear in your manuscript. From the difference of time between CPU time and Wall-clock time that you obtain with DSK, it seems that it was run using several threads. In order to obtain a balanced comparison with Bifrost which uses a single thread from FASTA to output graph when using option `-t 1`, I think DSK should be run with one thread too  when you report its running time in the manuscript.

2 - I understand now where the difference of vertices and edges cardinality come from. I was mistaken because the flag DADD_REVCOMPS in not mentioned in the README.
I haven't run DynBOSS again without the flag DADD_REVCOMPS. However, I ran DynBOSS on a completely different machine equipped with an SSD hard drive this time (with flag DADD_REVCOMPS). I obtain the following:
```
./dynboss/cosmo-build-dyn s_6.solid_kmers_binary.packed
k             : 31
num_nodes()   : 620676646
num_edges()   : 642073709
Total size    : 431.472 MB
Bits per edge : 5.63712 Bits
	Command being timed: ./dynboss/cosmo-build-dyn s_6.solid_kmers_binary.packed"
	User time (seconds): 3437.70
	System time (seconds): 1.08
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 57:19.02
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 932040
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1
	Minor (reclaiming a frame) page faults: 232378
	Voluntary context switches: 318
	Involuntary context switches: 4324
	Swaps: 0
	File system inputs: 836344
	File system outputs: 850040
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```
Even with a much faster hard drive, I get a running time which is roughly 6 times larger than the one you reported in your answer for the same number of vertices and edges. Maybe you could run it too on a different machine and see if you still obtain the same running time?

Memory:

I understand now that you measured the size of the data structure in memory. The size of the data structure is a useful information to understand graph memory after construction but I think two very important information for the construction that are missing from Table 2 would be peak of RAM and disk usage during construction. In addition, I think that the size of the graph on disk is a misleading information as Bifrost outputs GFA which is a community supported format for assembly graph while all the other tools, BFT included, outputs a binary format (if I understood correctly).

Thank you for your help.

Guillaume

PS: I compiled dynBOSS run with GCC 5.3 the first time and with GCC 7.3 for this new machine so I don't think the compiler is the issue here.

**Comment by GuillaumeHolley** [comment]
Could you also share your file `lut.hpp`? I had some issues running the python script to generate it and I modified it by hand to make it run. I don't think its the issue since we have the same number of nodes and edges (with flag DADD_REVCOMPS) but we never know.

**Comment by baharpan** [comment]
Dear Guillaume,

I think I realized what was the problem. Please download the folder ‘include’ from the repository and compile all programs once again. This folder belongs to DYNAMIC library (https://github.com/xxsds/DYNAMIC) which DynamicBOSS is built upon. The authors have made a huge improvement a while ago, and even though I have used the updated version for running the experiments in the paper, it was not updated here. I updated this folder today, and I am pretty sure it will solve the time difference you experienced. 

Also upon your request, I run cosmo-build-dyn and Bifrost on another machine and below are the results:
```
#cosmo-build-dyn with flag DADD_REVCOMPS. 
#(This flag is not needed in these experiments hence, 
#the experiments in the paper are run without this flag 
#which cuts the runtime to 7min 7s.)
 
k             : 31
num_nodes()   : 620676646
num_edges()   : 642073709
Total size    : 446.054 MB
Bits per edge : 5.82763 Bits
	Command being timed: "cosmo-build-dyn 28M_e.solid_kmers_binary.packed"
	User time (seconds): 649.66
	System time (seconds): 5.76
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 10:55.56
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 904376
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 759136
	Voluntary context switches: 41
	Involuntary context switches: 1729
	Swaps: 0
	File system inputs: 3416
	File system outputs: 850040
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
 ```
```
#The new version of Bifrost

Command being timed: "bifrost build -t 1 -k 31 -o 28M_e-refbased.bfrst-test -r 28M_e.fa"
	User time (seconds): 4098.50
	System time (seconds): 52.90
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:09:19
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 3111772
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 54019017
	Voluntary context switches: 202
	Involuntary context switches: 7110
	Swaps: 0
	File system inputs: 15553544
	File system outputs: 4030896
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```
Which shows that the difference between the methods is consistent with the resulsts of the other machine.

**Comment by GuillaumeHolley** [comment]
Dear Bahar,

Thank you for having a look into those issues. I pulled the new folder `include` from the repository but now, compiling fails with the following error:
```
In file included from ./include//internal/spsi.hpp:27:0,
                 from ./include//dynamic.hpp:15,
                 from dynBoss.hpp:15,
                 from cosmo-build-dyn.cpp:13:
./include//internal/includes.hpp:27:31: fatal error: tsl/hopscotch_map.h: No such file or directory
compilation terminated.
make: *** [cosmo-build-dyn] Error 1
```

**Comment by baharpan** [comment]
Please try one more time now. Thanks.

**Comment by GuillaumeHolley** [comment]
The new version compiles thanks. This is what I get with the new version *without* the flag DADD_REVCOMPS:
```
$./dynboss/cosmo-pack ../s_6.solid_kmers_binary

User time (seconds): 223.37
System time (seconds): 6.34
Percent of CPU this job got: 98%
Elapsed (wall clock) time (h:mm:ss or m:ss): 3:53.68

memusg: peak=16523448

$./dynboss/cosmo-build-dyn s_6.solid_kmers_binary.packed 
k             : 31
num_nodes()   : 401314967
num_edges()   : 412730297
Total size    : 286.734 MB
Bits per edge : 5.82778 Bits

User time (seconds): 548.97
System time (seconds): 2.40
Percent of CPU this job got: 99%
Elapsed (wall clock) time (h:mm:ss or m:ss): 9:14.02

memusg: peak=581048
```

Time seems now consistent with what you had: ~13min. Memory usage without flag DADD_REVCOMPS decreased to 16.5 GB compared to the 23 GB with flag DADD_REVCOMPS.

However, the number of nodes and edges seems very different from what you had: 412730297 edges in my case versus 269218149 edges that you previously reported. I checked the graph produced by Bifrost and I get 208024371 canonical 31-mers which gives us another number... Any idea what is happening?

**Comment by baharpan** [comment]
You're welcome. 
There are some notes that I should mention:
1- The number of edges in DynamicBOSS is not equal to the number of kmers in the read set. The reason is that we create and add the dummy edges to maintain the BWT-based nature of DynamicBOSS (more explanation comes in the paper). Hence, we expect to see #edges > #kmers. 
2- If you don't want to use DADD_REVCOMPS, then kmer counting should be non-canonical. Otherwise, the graph will have (unnecessarily) more dummy edges. The DSK in the repository by default counts the non-canonical kmers. Do you use DSK in this repository? 

Below is the DSK results that I have: 
```
-------------------Counted kmers time Wallclock  1491.95 s
 
------------------ Counted kmers and kept those with abundance >=1,     
-------------------Total time Wallclock  1491.97 s
Total RAM: 773944 MB
 
Saved 243947156 solid kmers
 ```

These kmers (243947156) are non-canonical which should be different (larger) than the number of canonical kmers that Bifrost reports (208024371). Also, due to the addition of dummy edges, the number of the edges in DynamicBOSS (without flag DADD_REVCOMPS) should be 269218149. 
As I mentioned above, in case you have run DSK with the canonical setting, there is this chance that you get a larger graph, so please let me know if you get the same DSK results as mine. Thanks.

**Comment by GuillaumeHolley** [comment]
I did use the DSK from this repository:
```
./dsk-1.6906/dsk s_6.fastq 31
```
which gave me 244049367 solid k-mers.

**Comment by baharpan** [comment]
Thanks. Please try compiling DSK with "make dsk canon=0".

**Comment by GuillaumeHolley** [comment]
Dear Bahar,

With this last edit, I get the same numbers as you: 258318223 nodes / 269218149 edges. Also, `cosmo-pack` memory usage decreased to 4.05 GB.

Thank you for your help!
Guillaume
